### ISSUE TITLE
相关的依赖包

### ISSUE THREAD

**Issue by Cross-maxwell** [InfiniteTsukuyomi/PyMicroChat#5]
from google.protobuf.internal import decoder, encoder   #  这个依赖包，pycharm 总是报错

lib = loader("./microchat/dll/ecdh_x32.dll")   # 这个依赖的共享库/动态库，是从哪儿下载的呢？我想迁移到Linux 玩一玩

**Comment by BigBigXiong** [comment]
protobuf运行报错吗，ecdh_x32可以参考MicroChat项目的cpp工程https://github.com/InfiniteTsukuyomi/MicroChat/tree/master/test/ecdh，欢迎用python实现
