### ISSUE TITLE
打开验证页面时卡死

### ISSUE THREAD

**Issue by linshunxin** [InfiniteTsukuyomi/PyMicroChat#6]
使用pyMicroChat登陆时打开浏览器验证时窗口卡死。
使用旧版MicroChat却能登陆，但是有消息来的时候提示 协议需要更新。
大神这是什么情况？

streamer 2018-04-10 03:15:02,315    ERROR: 登陆结果:
code:-301
即将尝试切换DNS重新登陆!
streamer 2018-04-10 03:15:02,325     INFO: 正在重新登陆........................
streamer 2018-04-10 03:15:02,638    ERROR: 登陆结果:
code:-106
Error msg:系统检测到环境存在异常，为了你的帐号安全， 请轻触“确定”进行安全验证。

streamer 2018-04-10 03:15:02,641    ERROR: 请在浏览器授权后重新登陆!
QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
Failed to load opengl32sw.dll (Unknown error 0x000000c1.)
Failed to load and resolve WGL/OpenGL functions
QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
Failed to load opengl32sw.dll (Unknown error 0x000000c1.)
Failed to load and resolve WGL/OpenGL functions
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001
QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
Failed to load opengl32sw.dll (Unknown error 0x000000c1.)
Failed to load and resolve WGL/OpenGL functions
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.

**Comment by InfiniteTsukuyomi** [comment]
> This is most likely caused by not having the necessary graphics drivers installed.
内置的qt浏览器需要opengl的支持,建议检查opengl安装是否正确或换个环境试试.
如果一定要在此环境下测试，可根据Util.OpenIE函数的参数url手动在浏览器中完成授权再登录.
感谢！
